### ISSUE TITLE
Ports cannot sincronize baguette repo

### ISSUE THREAD

**Issue by ghost** [baguette/crux-ports#2] opened 2018-02-13 21:40 UTC
I followed all the steps to activate the repository, but I get the following error:

![virtualbox_2018-02-13_18-39-56](https://user-images.githubusercontent.com/11687827/36175192-66d21114-10ed-11e8-904b-b9608163f397.png)

**Comment by baguette** [comment] 2018-02-18 06:23
Hey, thanks for this report.

Unfortunately, I've not been keeping these ports up to date. I'll try look into this issue within the next few days, and hopefully update the ports while I'm at it.

—Cory

**Comment by baguette** [comment] 2018-02-26 14:24
I'm not able to reproduce this issue on the latest CRUX. Can you verify that `/usr/ports/baguette` exists and has the correct permissions? You should have something like this:

```
$ ls -ld /usr/ports/baguette/
drwxr-xr-x 69 root root 4096 Feb 26 09:17 /usr/ports/baguette/
```

**Comment by baguette** [comment] 2018-06-06 12:51
Closing this issue as I cannot reproduce it and have not received any further communication from originator for over 3 months now.

**Closed as completed by baguette** 2018-06-06 12:51 UTC
